// components/WorkCard.vue
<template>
  <div class="card">
    <div class="box">
      <n-link :to="'/works/'+arg.caption" prefetch>
        <!--個々の背景に画像 -->
        <img :src="'worksimg/'+arg.caption+'.png'" />
        <div class="card_content">
          <p class="title">{{arg.title}}</p>
          <p class="desc">{{arg.desc}}</p>
        </div>
      </n-link>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    arg: {
      type: Object,
      required: true
    }
  },
  data() {
    return {};
  },
  mounted() {}
};
</script>
<style scoped>
img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  z-index: 0;
  position: absolute;
}

.card .box {
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
}
.card {
  border-radius: 2px;
  overflow: hidden;
}
.card_content {
  position: absolute;
  z-index: 1;
  width: calc(100% - 5px);
  padding-left: 5px;
  height: 100%;
  top: 160px;
  transition-duration: 0.3s;
  background-color: rgba(255, 255, 255, 0.6);
}
.card_content .title {
  font-size: large;
  font-weight: 700;
  margin-top: 10px;

  margin-top: 5px;
  margin-bottom: 5px;
}
a .card_content .desc {
  transition-duration: 0.3s;
  opacity: 0;
  margin-top: 0;
  margin-bottom: 0;
}
.card .box:hover > a .card_content .desc {
  opacity: 1;
}
.card .box:hover > a .card_content {
  transform: translate(0px, -50px);
}

@media screen and (max-width: 450px) {
  .card_content .title {
    margin-top: 2px;
  }
  .card_content {
    padding-left: 3px;
    width: calc(100% - 3px);
    top: 155px;
  }
}
</style>

// components/WorkCard.tsx
import Link from 'next/link'
import Image from 'next/image'
import type { WorkMetadata } from '@/lib/content'

interface WorkCardProps {
  work: WorkMetadata
}

export default function WorkCard({ work }: WorkCardProps) {
  return (
    <div className="rounded-sm overflow-hidden h-full">
      <div className="w-full h-full relative overflow-hidden group">
        <Link href={`/works/${work.slug}`} className="block w-full h-full">
          <Image
            src={work.image || '/images/works/default.png'}
            alt={work.title}
            fill
            className="object-cover"
            loading="lazy"
            sizes="(max-width: 450px) 160px, 250px"
          />
          <div className="absolute z-10 w-[calc(100%-5px)] pl-[5px] h-full top-40 transition-transform duration-300 bg-white/60 group-hover:-translate-y-12 sm:w-[calc(100%-3px)] sm:pl-[3px] sm:top-[155px]">
            <p className="text-lg font-bold mt-[5px] mb-[5px] sm:mt-[2px]">
              {work.title}
            </p>
            <p className="mt-0 mb-0 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
              {work.description}
            </p>
          </div>
        </Link>
      </div>
    </div>
  )
}
