// app/about/page.tsx
'use client'

import Image from 'next/image'
import { useState, useEffect } from 'react'
import awards from '@/store/award.json'

interface Award {
  date: string
  detail: string
}

export default function AboutPage() {
  const [animePos, setAnimePos] = useState(0)

  const doAnime = () => {
    setAnimePos(Math.floor(Math.random() * 3))
  }

  useEffect(() => {
    const yumoanime = () => {
      const timeout = setTimeout(
        () => {
          doAnime()
          yumoanime()
        },
        (Math.floor(Math.random() * 6) + 5) * 1000
      )
      return timeout
    }

    const timeout = yumoanime()
    return () => clearTimeout(timeout)
  }, [])

  const getTransformY = () => {
    if (animePos === 0) return 0
    if (animePos === 1) return 40
    return 85
  }

  return (
    <div className="container mx-auto max-w-4xl">
      <div className="py-8">
        <div className="flex justify-center mb-4">
          <div
            className="w-[100px] h-[100px] rounded-full overflow-hidden relative cursor-pointer"
            style={{ backgroundColor: '#b6d55d' }}
            onClick={doAnime}
          >
            <Image
              src="/images/takex5g_transparent.png"
              width={100}
              height={100}
              alt="ゆうもや"
              className="absolute left-0 transition-transform duration-[800ms]"
              style={{ transform: `translateY(${getTransformY()}px)` }}
            />
          </div>
        </div>
        <h1 className="text-3xl font-bold text-center mb-6 font-display">
          ゆうもや
        </h1>
        <div className="mb-8 text-center space-y-4">
          <p>ハードウェアからWEBまで。ゆるふわものづくりをやってます</p>
          <p>
            様々なソフトウェアやハードウェア、時には最先端技術を使って創作を行い、
            <br className="hidden md:inline" />
            ユーモアセンスの溢れる面白いモノを作ります
          </p>
        </div>

        <div className="bg-gray-50 p-6 rounded-lg mb-8">
          <p className="font-semibold mb-2">メール</p>
          <p className="font-display mb-2">takex5g@mononichi.com</p>
          <p className="text-sm text-gray-600">
            （
            <a
              href="https://twitter.com/takex5g"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:underline"
            >
              Twitter
            </a>
            のDMもお使いください）
          </p>
        </div>

        <div className="flex justify-center gap-6 mb-12">
          <a
            href="https://twitter.com/takex5g"
            target="_blank"
            rel="noopener noreferrer"
            className="flex flex-col items-center gap-2 hover:opacity-70 transition-opacity"
          >
            <Image
              src="/images/twitter.svg"
              width={48}
              height={48}
              alt="Twitter"
            />
            <span className="font-display">Twitter</span>
          </a>
          <a
            href="https://github.com/takex5g"
            target="_blank"
            rel="noopener noreferrer"
            className="flex flex-col items-center gap-2 hover:opacity-70 transition-opacity"
          >
            <Image
              src="/images/github.svg"
              width={48}
              height={48}
              alt="GitHub"
            />
            <span className="font-display">GitHub</span>
          </a>
        </div>

        <div>
          <h2 className="text-2xl font-bold mb-6 font-display">
            受賞・出展など
          </h2>
          <table className="w-full">
            <tbody>
              {(awards.award as Award[]).map((award, index) => (
                <tr key={index} className="border-b border-gray-200">
                  <th className="py-3 px-2 text-left align-top font-normal text-sm whitespace-nowrap">
                    {award.date}
                  </th>
                  <td
                    className="py-3 px-2 text-sm"
                    dangerouslySetInnerHTML={{
                      __html: award.detail.replace(
                        /\[([^\]]+)\]\(([^)]+)\)/g,
                        '<a href="$2" class="text-blue-600 hover:underline">$1</a>'
                      ),
                    }}
                  />
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}

// pages/about.vue
<template>
  <div>
    <Header page="about" v-on:click-event="$router.push('/')" />
    <div class="container">
      <div class="contents">
        <div class="yumoya">
          <img
            :style="yumoyaanime"
            src="~/assets/img/takex5g_transparent.png"
            width="100px"
            height="100px"
            alt="ゆうもや"
          />
        </div>
        <p class="name">ゆうもや</p>
        <p>ハードウェアからWEBまで。ゆるふわものづくりをやってます</p>
        <p></p>
        <div style="padding: 10px" />
        メール
        <p class="Montserrat">{{ takex5g }}🐌mononichi.com</p>
        <div class="social">
          <div class="icon Montserrat">
            <a href="https://twitter.com/takex5g" target="_brank">
              <img src="~/assets/img/twitter.svg" alt="twitter" />
              <span>Twitter</span>
            </a>
          </div>
          <!-- <div class="icon Montserrat">
            <a href="https://www.tiktok.com/@takex5g" target="_brank">
              <img
                src="~/assets/img/tiktok.svg"
                
                alt="tiktok"
              />
              <span>TikTok</span>
            </a>
          </div> -->
          <div class="icon Montserrat">
            <a href="https://github.com/takex5g" target="_brank">
              <img src="~/assets/img/github.svg" alt="github" />
              <span>GitHub</span>
            </a>
          </div>
          <div class="icon Montserrat">
            <a href="https://note.com/takex5g" target="_brank">
              <img src="~/assets/img/note.png" alt="note" />
              <span>note</span>
            </a>
          </div>
        </div>
        <!-- <div>
          <h2>使用技術</h2>
          <p>Nuxt.js,</p>
        </div> -->
        <div class="award">
          <h2>受賞・出展など</h2>
          <table>
            <tbody>
              <tr v-for="(content, index) in award" :key="index">
                <th>{{ content.date }}</th>
                <td v-html="$md.render(content.detail)" />
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Header from "@/components/Header";
import award from "~/store/award.json";
export default {
  components: { Header },
  head() {
    return {
      title: "About",
    };
  },
  asyncData(context) {
    //jsonからデータを読みだし
    return {
      award: award.award, //生データ
    };
  },
  data: function () {
    return {
      takex5g: "takex5g",
      anime: 0,
    };
  },
  methods: {
    doanime() {
      var self = this;
      this.anime = Math.floor(Math.random() * 3);
      setTimeout(() => {
        self.anime = Math.floor(Math.random() * 3);
      }, 1 * 1000);
      setTimeout(() => {
        self.anime = Math.floor(Math.random() * 2);
      }, 1 * 2000);
    },
    yumoanime() {
      var self = this;
      setTimeout(() => {
        self.doanime();
        self.yumoanime();
      }, (Math.floor(Math.random() * 10) + 5) * 1000);
    },
  },
  mounted() {
    this.yumoanime();
  },
  computed: {
    yumoyaanime: function () {
      var pos = 0;
      if (this.anime == 0) pos = 0;
      else if (this.anime == 1) pos = 40;
      else if (this.anime == 2) pos = 85;
      return {
        transform: "translate(0px, " + pos + "px)",
      };
    },
  },
};
</script>

<style lang="scss" scoped>
.award {
  /*受賞歴等 */
  max-width: 700px;
  margin: auto;
  padding: 90px 0 30px 0;
  table {
    text-align: left;
    th {
      //見出し
      font-weight: bold;
      padding: 10px 15px 10px 0;
    }
    td {
      //文章
      font-weight: normal;
      &::v-deep * {
        margin: 0;
      }
    }
  }
}

.yumoya {
  width: 100px;
  height: 100px;
  background: #b6d55d;
  border-radius: 50%;
  margin: auto;
  overflow: hidden;
  transition: 0.8s;
  position: relative;
  z-index: 1;
}
.yumoya img {
  left: 0px;
  transition: 0.8s;
  top: 0px;
  position: absolute;
}

.container {
  margin: auto;
  margin-top: 60px;
  padding: 0 20px 0 20px;
}
.contents {
  width: 100%;
  text-align: center;
  margin: 0 auto;
}
.name {
  font-weight: 700;
}
.social {
  display: flex;
  justify-content: center;
  margin-top: 50px;
  transition: 0.3s;

  a {
    text-decoration: none;
  }
}
.social:hover {
  opacity: 0.8;
}

.social .icon * {
  vertical-align: middle;
}
.icon {
  margin: 20px;
  img {
    width: 22px;
    height: 22px;
  }
}
</style>
